describe('Settings Page', function () {
   beforeEach('UI',()=>{
      cy.viewport('macbook-11')
   })
   it('Sign in', function () {
      cy.visit('https://deliverydev.quickeats.co.uk/login')
      cy.get('input[type="email"]').type('khanmuhammadmalik@gmail.com').get('[type="password"]').type('123456')
      cy.get('[type="checkbox"]').check()
      cy.get('.btn').contains('Sign in').should('be.visible').click() 
   })
   // it('Settings & Rate list view', function () {
   //        cy.get('[id="2"]').click().xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[1]/a').click()
   //        cy.get('.btn[class="btn btn-sm btn-primary align-self-center"]').contains('Add Rate').click()
   //        cy.get(':nth-child(2) > .form-control').select(1)
   //        cy.get(':nth-child(3) > .form-control').type(20)
   //        cy.get(':nth-child(4) > .form-control').type(25)
   //        cy.get(':nth-child(5) > .form-control').type(15)
   //        cy.get('form > :nth-child(6)').get(':nth-child(6) > #flexCheckDefault').check()
   //        cy.get('form > :nth-child(7)').get(':nth-child(7) > #flexCheckDefault').click()
   //        cy.get('form > :nth-child(8)').get(':nth-child(8) > #flexCheckDefault').check()
   //        cy.get(':nth-child(9) > .form-control').select(2)
   //        cy.get('.btn[class="w-100 btn btn-lg btn-primary"]').contains('Submit').click()
   //        cy.go('back').wait(3000)
   //  })
   //  it('Add Rate',function(){
   //    cy.get('[id="2"]').click().xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[1]/a')
   //    cy.get(':nth-child(11) > :nth-child(11) > .btn-group > .btn-primary').contains('View').should('be.visible').click({force:true}).wait(2000)
   //    //cy.get('.btn[class="btn btn-sm btn-primary me-2"]').contains('View').should('be.visible').click({force: true}).wait(2000)
   //    cy.get(':nth-child(12) > td > .overflow-hidden > .btn').contains('Add Rate Range').should('be.visible').click({force:true}).wait(2000)
   //    cy.get('input[placeholder="Start Range"]').type(6.5)
   //    cy.get('input[placeholder="End Range"]').type(10.0)
   //    cy.get('input[placeholder="Range Price"]').type(100)
   //    cy.get(':nth-child(5) > .form-control').select(0)
   //    cy.get('.btn[class="w-100 btn btn-lg btn-primary"]').contains('Submit').click().wait(2000)
   //    cy.get(':nth-child(6) > .btn-group > .btn-secondary').contains('Edit').should('be.visible').click()
   //    cy.get('input[placeholder="Range Price"]').should('have.value','100.00').clear().type('150')
   //    cy.get('.btn[class="w-100 btn btn-lg btn-primary"]').contains('Submit').click()
   //    cy.go('back').wait(3000)
   // })
   // it('Create pakages',function(){
   //    cy.get('[id="2"]').click().xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[1]/a').click()
   //    cy.get('.show > :nth-child(2) > .nav-link').click()
   //     cy.get('.btn[class="btn btn-sm btn-primary align-self-center"]').contains('Add Package').click()
   //     cy.get('form > :nth-child(2) > .form-control').type('tester title')
   //     cy.get(':nth-child(3) > .form-control').type('tester lable')
   //     cy.get(':nth-child(4) > .form-control').type('tester detail')
   //     cy.xpath('//*[@id="app"]/div/div/div[2]/main/main/form/div[4]/div/label').selectFile("cypress/fixtures/download.jpg")
   //     cy.xpath('//*[@id="app"]/div/div/div[2]/main/main/form/div[5]/input').click().type('300')
   //     cy.xpath('//*[@id="app"]/div/div/div[2]/main/main/form/div[6]/select').select(1)
   //     cy.xpath('//*[@id="app"]/div/div/div[2]/main/main/form/button').contains('Submit').should('be.visible').click().wait(2000)
   // })
   it('edit pakage', ()=>{
       cy.get('[id="2"]').click().xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[1]/a').click()
       cy.xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[2]/a').click()
       cy.get('tbody > :nth-child(2) > :nth-child(8)').xpath('//*[@id="app"]/div/div/div[2]/main/div/div/div[3]/div/table/tbody/tr[2]/td[8]/div/a[1]').contains("Edit").click({ force: true })
       cy.wait(3000) 
       cy.get(':nth-child(1) > .form-control').clear().type('Pakage edit')
       cy.get('form > :nth-child(2) > .form-control').clear().type('Lable edit')
       cy.get(':nth-child(3) > .form-control').clear().type('Detail edit')
       cy.get('.input-group > .form-control').clear().xpath('//*[@id="app"]/div/div/div[2]/main/div/div/div[2]/form/div[4]/div/label').selectFile("cypress/fixtures/images.png")
       cy.get(':nth-child(5) > .form-control').clear().type(250)
       cy.get(':nth-child(6) > .form-control').select(3)
       cy.xpath('//*[@id="app"]/div/div/div[2]/main/div/div/div[2]/form/button').contains('Submit').should('be.visible').click().wait(2000)
   })
   // it('Add Country',function(){
   //   cy.xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[6]/a').click()
   //   cy.get('.bg-light > .d-flex').click()
   //   cy.get('.btn[class="btn btn-sm btn-primary align-self-center"]').contains('Add Country').click()
   //   cy.get(':nth-child(1) > .form-control').type('Indonisia')
   //   cy.get(':nth-child(2) > .form-control').type('+62')
   //   cy.get(':nth-child(3) > .form-control').type('Rp')
   //   cy.get(':nth-child(4) > .form-control').type('Indonesia')
   //   cy.get(':nth-child(5) > .form-control').type('GMT+7')
   //   cy.get(':nth-child(6) > .form-control').type('inonisa')
   //   cy.get(':nth-child(7) > .form-control').type('IDN')
   //   cy.get(':nth-child(8) > .form-control').select(1)
   //   cy.get('.form-check').get('#flexCheckDefault').check()
   //   cy.xpath('//*[@id="app"]/div/div/div[2]/main/div/div/div[2]/form/button').contains('Submit').should('be.visible').click().wait(2000)
   // })
   it('Edit Country',function(){
      cy.xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[11]/ul/li[6]/a').click().wait(2000)
      // cy.get('tbody > :nth-child(5)').get(':nth-child(5) > :nth-child(9) > .btn-group > .btn-secondary').click().wait(3000)
      // cy.get(':nth-child(1) > .form-control').clear().type('Dubai')
      // cy.get(':nth-child(2) > .form-control').clear().type('971')
      // cy.get(':nth-child(3) > .form-control').clear().type('AED')
      // cy.get(':nth-child(4) > .form-control').clear().type('Dubai')
      // cy.get(':nth-child(5) > .form-control').clear().type('GMT+4')
      // cy.get(':nth-child(6) > .form-control').clear().type('Dubai')
      // cy.get(':nth-child(7) > .form-control').clear().type('AE')
      // cy.get(':nth-child(8) > .form-control').select(1)
      // cy.get('.form-check').get('#flexCheckDefault').check()
      // cy.xpath('//*[@id="app"]/div/div/div[2]/main/div/div/div[2]/form/button').contains('Submit').should('be.visible').click().wait(2000)
      cy.get('.row > :nth-child(3)').get('td').should('have.text', "29")
   })
}) 