describe('Settings Page', function () {
    it('Sign in', function () {
       cy.visit('https://deliverydev.quickeats.co.uk/login')
       cy.get('input[type="email"]').type('khanmuhammadmalik@gmail.com').get('[type="password"]').type('123456')
       cy.get('[type="checkbox"]').check()
       cy.get('.btn').contains('Sign in').should('be.visible').click() 
    })
    it('Settings & Country Page', function () {
       cy.get('[id="2"]').click().xpath('//*[@id="app"]/div/div/div[1]/nav/ul/li[8]/ul/li[6]/a').click()
    })
    it('Create Country', function () {       
       cy.get('.btn[class="btn btn-sm btn-primary align-self-center"]').contains('Add Country').click()
       cy.get(':nth-child(1) > .form-control').click({force: true}).type('Test')
       cy.get(':nth-child(2) > .form-control').click({force: true}).type('12345')
       cy.get(':nth-child(3) > .form-control').click({force: true}).type('TS')
       cy.get(':nth-child(4) > .form-control').click({force: true}).type('TS')
       cy.get(':nth-child(5) > .form-control').click({force: true}).type('+5')
       cy.get(':nth-child(6) > .form-control').click({force: true}).type('Testing')
       cy.get(':nth-child(7) > .form-control').click({force: true}).type('Test123')
       cy.get(':nth-child(8) > .form-control').select(0)
       cy.get('#flexCheckDefault').check()
       cy.get('.w-100').contains('Submit').click().wait(1000)
    })
    it('Update Created Country', function () {
       cy.get('.row > :nth-child(3)').last()
       cy.get(':nth-child(10) > :nth-child(9) > .btn-group > .btn-secondary').contains('Edit').click().wait(1000)
       cy.get(':nth-child(7) > .form-control').click({force: true}).type('Test123')
       cy.get(':nth-child(8) > .form-control').select(1)
       cy.get('.w-100').contains('Submit').click().wait(1000)
    })
    it('Delete Created Country', function () {
       cy.get('.row > :nth-child(3)').last()
       cy.get(':nth-child(10) > :nth-child(9) > .btn-group > .btn-danger').contains('Delete').dblclick()
     })
})